env:
  node: true
  es2021: true
extends:
  - airbnb-base
  - prettier
parserOptions:
  ecmaVersion: 13
  sourceType: module
plugins:
  - prettier
rules: 
  no-console: 0
  prettier/prettier: 
    - error
    - singleQuote: true
  import/extensions:
    - error
    - ignorePackages
    - js: always
