name: lint-check
on: push
jobs:
  lint-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - name: install deps
        run: make install
      - name: Run linter
        run: make lint
